default:
  base_dir: .

constants:
  TARGET_VARIABLE: "odds.spread_close"
  TWO_YEARS_IN_DAYS: 730
  MAX_DAYS_SINCE_GAME: 728
  CUTOFF_DATE: '2015-09-01'
  END_DATE: '2023-11-07'
  BASE_COLUMNS: "scripts.all_columns.ALL_COLUMNS"
  AWAY_PREFIX: "statistics.away."
  HOME_PREFIX: "statistics.home."
  GAMES_DB_NAME: "games"
  TEAMS_DB_NAME: "teams"
  PREGAME_DB_NAME: "pre_game_data"
  RANKS_DB_NAME: "team_aggregated_metrics"
  DATE_FLEXIBILITY: 1

nfl_api:
  base_url: "https://api.sportradar.us/nfl/official/trial/v7/en/games"
  api_key: "bjudbnhmwxce3bumy5qprhhe"
  endpoint_schedule: "/{year}/{season}/schedule.json"
  endpoint_stats: "/{game_id}/stats.json"

paths:
  model_dir: "./models"
  json_dir: "./data/jsons"
  data_dir: "./data"
  static_dir: "./flask_app/static"
  template_dir: "./flask_app/templates"
  odds_dir: "./data/csvs/odds.csv"

database:
  mongo_uri: "mongodb+srv://mikefuscoletti:sERswgdHNxTxCKrd@cluster0.o9lx9sb.mongodb.net/?retryWrites=true&w=majority"
  database_name: "nfl_db"

model_settings:
  model_type: lasso
