default:
  base_dir: .

database:
  database_name: "nfl_data.db"

nfl_api:
  base_url: "https://api.sportradar.us/nfl/official/trial/v7/en/games"
  api_key: "ymuwdu4r4pbayf8n32h5ppxh"
  endpoint_schedule: "/{year}/{season}/schedule.json"
  endpoint_stats: "/{game_id}/stats.json"


model:
  model_dir: "${default.base_dir}/models"
