default:
  base_dir: .

constants:
  TARGET_VARIABLE: "odds_spread"
  TWO_YEARS_IN_DAYS: 730
  MAX_DAYS_SINCE_GAME: 728
  CUTOFF_DATE: '2019-09-01'
  BASE_COLUMNS: "scripts.all_columns.ALL_COLUMNS"
  AWAY_PREFIX: "statistics_away."
  HOME_PREFIX: "statistics_home."
  GAMES_DB_NAME: "games"
  TEAMS_DB_NAME: "teams"
  RANKS_DB_NAME: "team_aggregated_metrics"
  WASHINGTON: "Commanders"
  DATE_FLEXIBILITY: 1

nfl_api:
  base_url: "https://api.sportradar.us/nfl/official/trial/v7/en/games"
  api_key: "pvuwb272w345p6gkkzpytjd7"
  endpoint_schedule: "/{year}/{season}/schedule.json"
  endpoint_stats: "/{game_id}/stats.json"

paths:
  model_dir: "./models"
  json_dir: "./data/jsons"
  data_dir: "./data"
  static_dir: "./flask_app/static"
  template_dir: "./flask_app/templates"
  odds_dir: "./data/csvs/odds.csv"

database:
  mongo_uri: "mongodb://localhost:27017/"
  database_name: "nfl_db"

model_settings:
  model_type: "random_forest"
  grid_search:
    n_estimators: [100]
    max_depth: [None]
