default:
  base_dir: .

nfl_api:
  base_url: "https://api.sportradar.us/nfl/official/trial/v7/en/games"
  api_key: "ymuwdu4r4pbayf8n32h5ppxh"
  endpoint_schedule: "/{year}/{season}/schedule.json"
  endpoint_stats: "/{game_id}/stats.json"

paths:
  model_dir: "./models"
  json_dir: "./data/jsons"
  data_dir: "./data"
  static_dir: "./flask_app/static"
  template_dir: "./flask_app/templates"

database:
  mongo_uri: "mongodb://localhost:27017/"
  database_name: "nfl_db"
