# constants.py

# List of column names to keep
COLUMNS_TO_KEEP = [
    "odds.spread_close",
    "passing.totals.air_yards_difference",
    "passing.totals.blitzes_difference",
    "passing.totals.cmp_pct_ratio",
    "passing.totals.dropped_passes_difference",
    "passing.totals.net_yards_difference",
    "rushing.totals.attempts_difference",
    "rushing.totals.redzone_attempts_difference",
    "rushing.totals.yards_difference",
    "rushing.totals.yards_after_contact_difference",
    "receiving.totals.catchable_passes_difference",
    "receiving.totals.dropped_passes_difference",
    "receiving.totals.longest_difference",
    "summary.avg_gain_ratio",
    "summary.lost_fumbles_difference",
    "summary.penalty_yards_difference",
    "summary.total_yards_difference",
    "efficiency.fourthdown.attempts_difference",
    "efficiency.fourthdown.pct_ratio",
    "efficiency.goaltogo.attempts_difference",
    "defense.totals.fumble_recoveries_difference",
    "defense.totals.hurries_difference",
    "defense.totals.passes_defended_difference",
    "advanced.drop_rate_difference",
    "advanced.pressure_rate_on_qb_difference",
    "extra_points.conversions.totals.defense_successes_difference",
    "extra_points.conversions.totals.pass_successes_difference",
    "extra_points.kicks.totals.attempts_difference",
    "field_goals.totals.blocked_difference",
    "first_downs.penalty_difference",
    "fumbles.totals.fumbles_difference",
    "fumbles.totals.opp_rec_yards_difference",
    "int_returns.totals.avg_yards_difference",
    "kickoffs.totals.onside_attempts_difference",
    "kickoffs.totals.onside_successes_difference",
    "penalties.totals.yards_difference",
    "punt_returns.totals.faircatches_difference",
    "punt_returns.totals.yards_difference",
    "punts.totals.avg_net_yards_ratio",
    "punts.totals.avg_yards_ratio",
    "touchdowns.fumble_return_difference",
    "touchdowns.int_return_difference",
    "touchdowns.punt_return_difference",
]
