# constants.py

# List of column names to keep
COLUMNS_TO_KEEP = [
    "scoring_differential",
    "statistics_home.summary.possession_time",
    "statistics_away.summary.possession_time",
    "statistics_home.summary.avg_gain",
    "statistics_away.summary.avg_gain",
    "statistics_home.summary.safeties",
    "statistics_away.summary.safeties",
    "statistics_home.summary.turnovers",
    "statistics_away.summary.turnovers",
    "statistics_home.summary.play_count",
    "statistics_away.summary.play_count",
    "statistics_home.summary.rush_plays",
    "statistics_away.summary.rush_plays",
    "statistics_home.summary.total_yards",
    "statistics_away.summary.total_yards",
    "statistics_home.summary.fumbles",
    "statistics_away.summary.fumbles",
    "statistics_home.summary.lost_fumbles",
    "statistics_away.summary.lost_fumbles",
    "statistics_home.summary.penalties",
    "statistics_away.summary.penalties",
    "statistics_home.summary.penalty_yards",
    "statistics_away.summary.penalty_yards",
    "statistics_home.summary.return_yards",
    "statistics_away.summary.return_yards",
]
