# constants.py

# List of column names to keep
COLUMNS_TO_KEEP = [
    "odds.spread_close",
    "passing.totals.interceptions_difference",
    "passing.totals.longest_difference",
    "passing.totals.net_yards_difference",
    "passing.totals.pocket_time_difference",
    "passing.totals.sacks_difference",
    "rushing.totals.avg_yards_ratio",
    "rushing.totals.kneel_downs_difference",
    "rushing.totals.scrambles_difference",
    "rushing.totals.tlost_difference",
    "rushing.totals.yards_difference",
    "receiving.totals.catchable_passes_difference",
    "receiving.totals.yards_after_contact_difference",
    "summary.penalties_difference",
    "summary.safeties_difference",
    "efficiency.thirddown.successes_difference",
    "defense.totals.hurries_difference",
    "advanced.defensive_line_rating_difference",
    "advanced.offensive_line_rating_difference",
    "extra_points.conversions.totals.pass_successes_difference",
    "field_goals.totals.attempts_difference",
    "field_goals.totals.blocked_difference",
    "field_goals.totals.net_attempts_difference",
    "field_goals.totals.yards_difference",
    "int_returns.totals.touchdowns_difference",
    "interceptions.number_difference",
    "interceptions.returned_difference",
    "kick_returns.totals.touchdowns_difference",
    "kickoffs.totals.out_of_bounds_difference",
    "kickoffs.totals.touchbacks_difference",
    "misc_returns.totals.number_difference",
]
